version: '3.8'

services:
  nutrition-service:
    build: .
    container_name: nutrition_service_evander
    ports:
      - "8085:80"
    environment:
      CI_ENVIRONMENT: development
      APP_BASEURL: "http://localhost:8085/"
      JWT_SECRET: "supersecretkey1234567890supersecretkey"
    restart: always
